# create your drupal and postgres config here, based off the last assignment
# version: '2'

services:
  drupal:
    image: drupal:9
    ports:
      - "8080:80" # checked in docker image inspect drupal:9 (config - exposed ports)
    volumes: ## copied from https://hub.docker.com/_/drupal
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=mypasswd
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: